[anomaly_detection]
scale_score_lambda = 0.5719744244455544
anomaly_ratio = 1.0

[data]
tain_val_len = 2520
train_ratio = 0.8
seq_len = 128
patch_size = 8
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 2
wavelet = "coif2"
mode = "symmetric"

[model.CFM]
num_layers = 3
d_cf = 32
d_model = 96
num_heads = 4
d_head = 64
d_ff = 128
dropout = 0.16706092815407042
attention_dropout = 0.10624747417119573
num_gat_heads = 2
gat_head_dim = 16
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.0008431759429337677
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.060622495150417864
ccd_align_lambda = 1.324455615655966
scale_loss_lambda = 0.7637591906832208
ccd_loss_lambda = 0.008161114553726083
time_loss_delta = 1.0
scale_loss_delta = 1.0
