[anomaly_detection]
scale_score_lambda = 0.87
anomaly_ratio = 1.0

[data]
tain_val_len = 2520
train_ratio = 0.8
seq_len = 128
patch_size = 16
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 3
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 3
d_cf = 64
d_model = 64
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.141
attention_dropout = 0.176
num_gat_heads = 2
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00017
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.346
ccd_align_lambda = 0.897
scale_loss_lambda = 0.885
ccd_loss_lambda = 0.00064
time_loss_delta = 1.0
scale_loss_delta = 1.0
