[project]
name = "tsad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "ptwt>=0.1.9",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
