[anomaly_detection]
scale_score_lambda = 0.2
anomaly_ratio = 1.8049417168976782
threshold_strategy = "percentile"
aggregation_method = "weighted_max"

[data]
train_ratio = 0.8
seq_len = 128
patch_size = 16
patch_stride = 8

[model.FM]
affine = false
subtract_last = false
level = 3
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 3
d_cf = 96
d_model = 96
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.20944211840084767
attention_dropout = 0.1762196088417547
num_gat_heads = 4
gat_head_dim = 16
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.0014228662379900847
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.4567678604043635
ccd_align_lambda = 1.9961134627574981
scale_loss_lambda = 0.5510668095495663
ccd_loss_lambda = 0.08785213264701018
time_loss_delta = 1.0
scale_loss_delta = 1.0
