[anomaly_detection]
scale_score_lambda = 0.11699373857163789
anomaly_ratio = 1.0
threshold_strategy = "adaptive"
aggregation_method = "weighted_max"

[data]
train_ratio = 0.8
seq_len = 128
patch_size = 32
patch_stride = 8

[model.FM]
affine = false
subtract_last = false
level = 4
wavelet = "coif2"
mode = "symmetric"

[model.CFM]
num_layers = 5
d_cf = 64
d_model = 64
num_heads = 4
d_head = 64
d_ff = 128
dropout = 0.1587973272047787
attention_dropout = 0.18662878487279966
num_gat_heads = 4
gat_head_dim = 16
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = true
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.0031084009450684223
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.4529787432643022
ccd_align_lambda = 1.0847057548489554
scale_loss_lambda = 0.49752832942487013
ccd_loss_lambda = 0.005340959567129196
time_loss_delta = 1.0
scale_loss_delta = 1.0
