[anomaly_detection]
scale_score_lambda = 0.132
anomaly_ratio = 5.0
score_aggregation_alpha = 0.172

[data]
tain_val_len = 13104
train_ratio = 0.8
seq_len = 64
patch_size = 16
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 2
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 6
d_cf = 32
d_model = 256
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.392
attention_dropout = 0.375
num_gat_heads = 4
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = true
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 8e-05
weight_decay = 0.01876
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.413
ccd_align_lambda = 1.352
scale_loss_lambda = 0.92
ccd_loss_lambda = 0.00176
time_loss_delta = 1.0
scale_loss_delta = 1.0
