[anomaly_detection]
scale_score_lambda = 0.869
anomaly_ratio = 5.0
score_aggregation_alpha = 0.282

[data]
tain_val_len = 13104
train_ratio = 0.8
seq_len = 64
patch_size = 16
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 2
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 4
d_cf = 32
d_model = 256
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.368
attention_dropout = 0.273
num_gat_heads = 2
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = true
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00023
weight_decay = 0.0423
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.468
ccd_align_lambda = 1.329
scale_loss_lambda = 0.986
ccd_loss_lambda = 0.00021
time_loss_delta = 1.0
scale_loss_delta = 1.0
