[anomaly_detection]
scale_score_lambda = 0.464
anomaly_ratio = 1.0
score_aggregation_alpha = 0.884

[data]
tain_val_len = 13104
train_ratio = 0.8
seq_len = 128
patch_size = 16
patch_stride = 8

[model.FM]
affine = false
subtract_last = false
level = 2
wavelet = "coif2"
mode = "symmetric"

[model.CFM]
num_layers = 4
d_cf = 96
d_model = 256
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.163
attention_dropout = 0.133
num_gat_heads = 2
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = true
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00131
weight_decay = 0.03941
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.354
ccd_align_lambda = 1.614
scale_loss_lambda = 0.204
ccd_loss_lambda = 0.00146
time_loss_delta = 1.0
scale_loss_delta = 1.0
