[anomaly_detection]
scale_score_lambda = 0.623
anomaly_ratio = 1.0

[data]
tain_val_len = 2520
train_ratio = 0.8
seq_len = 64
patch_size = 32
patch_stride = 8

[model.FM]
affine = false
subtract_last = false
level = 4
wavelet = "coif2"
mode = "symmetric"

[model.CFM]
num_layers = 7
d_cf = 96
d_model = 128
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.125
attention_dropout = 0.125
num_gat_heads = 4
gat_head_dim = 16
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 2
learning_rate = 7e-05
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.154
ccd_align_lambda = 1.32
scale_loss_lambda = 0.627
ccd_loss_lambda = 0.00053
time_loss_delta = 1.0
scale_loss_delta = 1.0
