[anomaly_detection]
scale_score_lambda = 0.474
anomaly_ratio = 1.0
score_aggregation_alpha = 0.865

[data]
tain_val_len = 2520
train_ratio = 0.8
seq_len = 128
patch_size = 8
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 2
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 5
d_cf = 32
d_model = 128
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.218
attention_dropout = 0.163
num_gat_heads = 4
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = true
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00013
weight_decay = 0.04055
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.286
ccd_align_lambda = 1.486
scale_loss_lambda = 0.691
ccd_loss_lambda = 0.00043
time_loss_delta = 1.0
scale_loss_delta = 1.0
