[anomaly_detection]
scale_score_lambda = 0.199
anomaly_ratio = 1.0
score_aggregation_alpha = 0.543

[data]
tain_val_len = 3604
train_ratio = 0.8
seq_len = 64
patch_size = 16
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 4
wavelet = "sym4"
mode = "symmetric"

[model.CFM]
num_layers = 3
d_cf = 96
d_model = 128
num_heads = 4
d_head = 64
d_ff = 128
dropout = 0.203
attention_dropout = 0.348
num_gat_heads = 4
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00083
weight_decay = 0.00032
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.176
ccd_align_lambda = 1.453
scale_loss_lambda = 0.686
ccd_loss_lambda = 0.09834
time_loss_delta = 1.0
scale_loss_delta = 1.0
