[anomaly_detection]
scale_score_lambda = 0.207
anomaly_ratio = 5.0
score_aggregation_alpha = 0.294

[data]
tain_val_len = 58317
train_ratio = 0.8
seq_len = 64
patch_size = 32
patch_stride = 4

[model.FM]
affine = false
subtract_last = false
level = 4
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 4
d_cf = 64
d_model = 64
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.241
attention_dropout = 0.375
num_gat_heads = 2
gat_head_dim = 8
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 32
num_epochs = 30
learning_rate = 0.00025
weight_decay = 0.03144
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.089
ccd_align_lambda = 0.928
scale_loss_lambda = 0.573
ccd_loss_lambda = 0.0067
time_loss_delta = 1.0
scale_loss_delta = 1.0
