[anomaly_detection]
scale_score_lambda = 0.2
anomaly_ratio = 1.7600896070880767
threshold_strategy = "adaptive"
aggregation_method = "mean"

[data]
train_ratio = 0.8
seq_len = 128
patch_size = 16
patch_stride = 8

[model.FM]
affine = false
subtract_last = false
level = 3
wavelet = "db4"
mode = "symmetric"

[model.CFM]
num_layers = 4
d_cf = 64
d_model = 96
num_heads = 2
d_head = 64
d_ff = 128
dropout = 0.21313157449458708
attention_dropout = 0.2737192017264256
num_gat_heads = 4
gat_head_dim = 16
gat_dropout_rate = 0.1

[model.TSRM]
is_flatten_individual = false
rec_head_dropout = 0.1

[training]
batch_size = 64
num_epochs = 1
learning_rate = 0.00014336069087102294
pct_start = 0.3
es_patience = 10
es_delta = 0.001

[loss]
ccd_align_temperature = 0.1
ccd_regular_lambda = 0.39141129208139713
ccd_align_lambda = 1.6659817653537714
scale_loss_lambda = 0.726605921215298
ccd_loss_lambda = 0.001852262835641228
time_loss_delta = 1.0
scale_loss_delta = 1.0
